# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Release ${{ matrix.mc-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.unsupported }}

    strategy:
      matrix:
        java-version: [17]
        mc-version: [1.21, 1.20.2, 1.19.2, 1.18.2, 1.17.1]
        unsupported: [false]


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Setup Spigot Build Environment for ${{ matrix.mc-version }}
        run: |
          test -d BuildTools || mkdir BuildTools
          cd BuildTools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev ${{ matrix.mc-version }}
          cd ..
      - name: Change target version to ${{ matrix.mc-version }}
        run: |
          chmod +x ./.github/workflow-files/change-ver.sh
          ./.github/workflow-files/change-ver.sh ${{ matrix.mc-version }}
      - name: Update version of maven file to ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=${VER_TAG:1}
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
      - name: Build with Maven
        run: mvn package
      - name: Rename package
        run: |
          mkdir releases
          mv target/BattlebotVerify-${VER_TAG:1}.jar releases/verifyagent-${VER_TAG:1}-mc${MC_VERSION}.jar
          test $UNSUPPORTED == "true" && mv releases/verifyagent-${VER_TAG:1}-mc${MC_VERSION}.jar releases/verifyagent-${VER_TAG:1}-mc${MC_VERSION}-unsupported.jar || exit 0
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
          MC_VERSION: ${{ matrix.mc-version }}
          UNSUPPORTED: ${{ matrix.unsupported }}
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASES_TOKEN }}
          file: releases/verifyagent-*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true